#!/usr/bin/env perl
# SPDX-Copyright: Copyright (c) Alberto Ruiz <aruiz@gnome.org>
# SPDX-License-Identifier: LGPL-2.1-or-later

# This script turns supported devices into a hwdb[0] file for
# udev to properly set the right device properties for userland

use strict;
use warnings;

if ($#ARGV + 1 != 2) {
    print "Usage: create_hwdb.pl supported_readers.txt output.hwdb\n";
    exit 1;
}

my $supported_readers = $ARGV[0];
my $hwdb_file = $ARGV[1];

open(my $readers, '<:encoding(UTF-8)', $supported_readers)
  or die "Could not open file '$supported_readers' $!";

open (my $hwdb, '+>:encoding(UTF-8)', $hwdb_file)
  or die "Could not open file '$hwdb_file' $!";

print { $hwdb } "# This file was generated by CCID: https://ccid.apdu.fr/\n";
print { $hwdb } "# Data imported from https://salsa.debian.org/rousseau/CCID/-/blob/master/readers/supported_readers.txt\n\n";

while (my $row = <$readers>) {
  if ($row =~ m/^0x/) {
    chomp $row;
    my ($vendor, $part, $desc) = split(/:/, $row, 3);
    $vendor =~ s/^0x//g;
    $part =~ s/^0x//g;
    print { $hwdb } "usb:v${vendor}p${part}*\n ID_MODEL_FROM_DATABASE=$desc\n\n"
  }
}

close $hwdb
